### ISSUE TITLE
Please consider joining forces with bordoni/fakerpress

### ISSUE THREAD

**Issue by COLABORATI** [trendwerk/faker#4]
Hi, you are reinventing [fakerpress](https://github.com/bordoni/fakerpress), but:
- fakerpress has more features (e.g. import images, set terms, delete fake data)
- fakerpress has no wp-cli implementation (if I am not missing anything)

So this actually looks like a **perfect** match - you could concentrate on the wp-cli implementation and I am sure everybody is happy about more features and multiple eyes looking at code. 

Please unite! Thanks!

**Comment by haroldangenent** [comment]
Thank you for your suggestion. I understand that it must seem like this is the perfect match.

However, I have created this package not to be able to use a command line interface for a Faker, but because I had a problem. I couldn't find an easy and simplistic and flexible enough faker I could use consistently in a team (including FakerPress).

Thought I'd share my solution for people that have the same problem.
